// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQs1DFSf_7JLVQFAcwtpzDyT9hoNwl4gQ',
    appId: '1:327820252718:web:355b065487295cd199b1bf',
    messagingSenderId: '327820252718',
    projectId: 'forensiq-16901',
    authDomain: 'forensiq-16901.firebaseapp.com',
    storageBucket: 'forensiq-16901.firebasestorage.app',
    measurementId: 'G-KLESBR8QXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkL9wLp3MaMJTJZVRdduNaFTojTCExtZM',
    appId: '1:327820252718:android:7cbb0b5fa873064b99b1bf',
    messagingSenderId: '327820252718',
    projectId: 'forensiq-16901',
    storageBucket: 'forensiq-16901.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh7_hw3aWV9RSV5KYy7ooJyY8j54wAg-k',
    appId: '1:327820252718:ios:82a609f9112c27dc99b1bf',
    messagingSenderId: '327820252718',
    projectId: 'forensiq-16901',
    storageBucket: 'forensiq-16901.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh7_hw3aWV9RSV5KYy7ooJyY8j54wAg-k',
    appId: '1:327820252718:ios:82a609f9112c27dc99b1bf',
    messagingSenderId: '327820252718',
    projectId: 'forensiq-16901',
    storageBucket: 'forensiq-16901.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQs1DFSf_7JLVQFAcwtpzDyT9hoNwl4gQ',
    appId: '1:327820252718:web:ed34c48206d995a899b1bf',
    messagingSenderId: '327820252718',
    projectId: 'forensiq-16901',
    authDomain: 'forensiq-16901.firebaseapp.com',
    storageBucket: 'forensiq-16901.firebasestorage.app',
    measurementId: 'G-7MC05ZZBML',
  );
}
